### ISSUE TITLE
Add git-lfs

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#13]
* download linux-amd64 from [releases](https://github.com/git-lfs/git-lfs/releases/latest)
* extract
* copy binary to path `/usr/local/bin` (alternate is using the included `install.sh`)
* run `git lfs install` as `ubuntu` user

blocks: https://github.com/renovatebot/renovate/issues/6842

We should use [other](https://github.com/git-lfs/git-lfs/wiki/Installation#other) install method, as its faster (install) that the apt version. We should also use this because the available version on ubuntu is old.

----
Ref https://github.com/renovatebot/docker-buildpack/issues/139

**Comment by fgblomqvist** [comment]
I'll attempt this one later today/tomorrow.

**Comment by fgblomqvist** [comment]
Potentially blocking https://github.com/renovatebot/renovate/issues/7894 as well.

**Comment by viceice** [comment]
fixed in #104
