### ISSUE TITLE
Add jsonnet-bundler

### ISSUE THREAD

**Issue by andrein** [containerbase/buildpack#195]
As part of https://github.com/renovatebot/renovate/pull/12720, I need to add support for jsonnet-bundler in buildpack.

Jsonnet-bundler can be installed in two ways, neither requires root.

1) `go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@v0.4.0`
2) [github release binary](https://github.com/jsonnet-bundler/jsonnet-bundler/releases/tag/v0.4.0)

**Comment by viceice** [comment]
ok, so we prefer github binary download.

you can use sbt as sample:
https://github.com/containerbase/buildpack/blob/main/src/usr/local/buildpack/tools/sbt.sh

**Comment by andrein** [comment]
Do I we need to support other architectures except amd64? jb also supports arm and arm64.

**Comment by rarkins** [comment]
We don't currently support non-amd64, although one day we should
