### ISSUE TITLE
Sign container images

### ISSUE THREAD

**Issue by JamieMagee** [containerbase/buildpack#201]
Signing generated containers allows end users to verify that any container they pull actually came from us. With GitHub Actions new support for OIDC [^1] it's now possible to use cosign [^2] to sign containers in GitHub Actions without any human interaction or storing long-lived keys as secrets.

Here's a demo someone put together explaining how to set it all up: https://github.com/chrisns/cosign-keyless-demo

[^1]: https://github.blog/changelog/2021-10-27-github-actions-secure-cloud-deployments-with-openid-connect/
[^2]: https://github.com/sigstore/cosign

**Comment by viceice** [comment]
Very interesing, needs some more refactoring of out docker builder to support this for all our images

**Comment by JamieMagee** [comment]
GitHub blog post on the same topic: https://github.blog/2021-12-06-safeguard-container-signing-capability-actions/
