### ISSUE TITLE
Use portable shebangs

### ISSUE THREAD

**Issue by JamieMagee** [containerbase/buildpack#27]
All of our tool install scripts (except `nix` :wink:) use the `#!/bin/bash` shebang, but these aren't portable, and aren't the best practice:tm:. Changing these to `#!/usr/bin/env bash` is a simple fix.

**Comment by viceice** [comment]
`#!/usr/bin/env bash` doesn't work on all platforms too, because `/usr/bin/env bash` can be missing too.

Also this tools only support ubuntu as distro, others are blocked.
