### ISSUE TITLE
User tool folders have wrong rights

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#304]
If installing a tool like npm as user, the npm folder has 755 but needs 775 as rights, so the root group can add tools when running with openshift.

- Ref whitesource/renovate-on-prem#193

**Comment by viceice** [comment]
Not all tool installer are using the fixed function. Eg `yarn` and `npm` are still broken.

@Chumper we need more e2e tests for openshift compabillity checks

**Comment by viceice** [comment]
https://github.com/containerbase/buildpack/blob/59f013a1ac8ca665647a2f0801b544bd89041ddb/src/usr/local/buildpack/tools/yarn.sh#L14

We need to call this there

https://github.com/containerbase/buildpack/blob/59f013a1ac8ca665647a2f0801b544bd89041ddb/src/usr/local/buildpack/utils/filesystem.sh#L26

**Comment by Chumper** [comment]
My plan was to use bats for new tools only, we can write test for old tools as well if needed.

**Comment by viceice** [comment]
> My plan was to use bats for new tools only, we can write test for old tools as well if needed.

No bat tests for old tools, just extend normal docker tests for popular tools.
