### ISSUE TITLE
elixir fails to install hex

### ISSUE THREAD

**Issue by eRez-ws** [containerbase/buildpack#309]
[Dockerfile.txt](https://github.com/containerbase/buildpack/files/8088501/Dockerfile.txt)
i'm building this Dockerfile (added `.txt` only so it won't be blocked when attaching to the issue), which includes installation of Erlang and Elixir.  
the build ends without any error, and after running the image, i can see that `mix` is installed, however `hex` is not installed, although the `elixir.sh` script includes the `hex` installation command

```
root@d63554929a9b:/# mix -v
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Mix 1.13.3 (compiled with Erlang/OTP 22)
root@d63554929a9b:/# mix hex
** (Mix) The task "hex" could not be found
Note no mix.exs was found in the current directory
```

`su -c 'mix local.hex --force' "${USER_NAME}"` - this is from `Elixir.sh`

**Comment by rarkins** [comment]
Are you a Hex user and familiar with how it works?

I'm not familiar with hex, so my first question is "who says `mix hex` is a valid command to work anyway?" Is it expected to work if you don't have any `mix.exs`?

FYI here's our buildpack test for elixir installation: https://github.com/containerbase/buildpack/blob/main/test/erlang/Dockerfile

**Comment by rarkins** [comment]
@eRez-ws if I take your Dockerfile and run it as non-root user then `mix hex` works

**Comment by rarkins** [comment]
You can achieve the same by also adding `USER 1000` at the end of the `Dockerfile`

**Comment by eRez-ws** [comment]
> USER 1000

works like a charm
