### ISSUE TITLE
[TESTS] Make Helm version in bats test renovatable

### ISSUE THREAD

**Issue by Chumper** [containerbase/buildpack#326]
Currently the bats tests for the helm tool are hardcoded and will not be versioned by Renovate.
We should enable all version in the bats tests to be automatically versioned by Renovate.

This probably requires a custom regex manager in the containerbase/.github repository.

Outcome of #300

**Comment by viceice** [comment]
Maybe we can resume the shell script regex manager config here.

**Comment by Chumper** [comment]
I created https://github.com/containerbase/.github/pull/8 for that.
Should be straight forward as it is basically the same
