### ISSUE TITLE
Cannot run Helm with non-root group anymore

### ISSUE THREAD

**Issue by maxbrunet** [containerbase/buildpack#334]
The image runs as `1000:0` (`ubuntu:root`) by default, I run it as `1000:1000` (`ubuntu:ubuntu`), and get errors:

```bash
/bin/sh: 1: helm: Permission denied
```

It appears to come from the content of the `/opt/buildpack` directory not being readable for others:

```bash
$ ls -l /opt/buildpack/
total 12
drwxrwx--- 2 root root 4096 Mar  7 21:33 env.d
drwxrwx--- 1 root root 4096 Mar 11 17:17 tools
drwxrwx--- 1 root root 4096 Mar 11 17:17 versions
```

It only seems to be used by Helm in the downstream [renovatebot/docker-renovate-full](https://github.com/renovatebot/docker-renovate-full) image:

```bash
/opt/buildpack/
├── env.d
├── tools
│   └── helm
│       └── 3.8.1
│           └── bin
│               ├── LICENSE
│               ├── README.md
│               └── helm
└── versions
    └── helm
```

The desired permissions would be `775` for directories and executables.

Not sure where that could be changed, around here maybe?:

https://github.com/containerbase/buildpack/blob/566925fdc9d5673693810fc3d67c1aebd9e25c9d/src/usr/local/buildpack/utils/constants.sh#L14-L17

Could have been caused by PR #300

**Comment by viceice** [comment]
I'm confused. The user 1000 should be a member of root group, check `/etc/groups`.

Not sure what's going wrong there.

**Comment by maxbrunet** [comment]
Nope, it is not:

```bash
$ docker run --rm containerbase/buildpack:3.11.1 grep root /etc/group
root:x:0:
```

And I do not think it should be, allowing running fully as non-root would be safer

**Comment by viceice** [comment]
Being a member of root group isn't a security issue. It's also the default on openshift.

So the solution is to explicit ad our user to the root group.

**Comment by maxbrunet** [comment]
The concern with using the root group is it may give write permissions to root files for a regular user which may not be desired by the end user.

Granting permissions to "others" allows to run as `1000:0` and `1000:1000`, giving the end user the choice in the uid/gid.

Just to mention it, I like to run containers with read-only file-system when possible, the least-privilege principle is important to me.

The OpenShift default may be a baseline, but it is not the most secured configuration, hardening is always possible.

If `ubuntu` is added to the `root` group, it comes back to the same as running the image as `1000:0`, so basically it would be similar to say running as `1000:1000` will not be supported

**Comment by viceice** [comment]
I think you are wrong, we had discussions about the root group and beeing a member of it isn't a security issue by default, as no file is writable by it by default on any linux distribution. So it isn't comparable by the root user.

We also will change the renovate full image to `binarySource=install` which won't work without beeing a member of root group.

So your requirement seems to be incompatible with our openshift compatibility requirements.

/cc @Chumper @rarkins

**Comment by Chumper** [comment]
Both approaches should work when we set the folders to `755` (root install) and `775` (non-root install).

In that case the requirements are:
* Installation needs to be done at least with the `root` group at minimum (for tools that allow installation as non-root)
* Installation needs to be done with the root user (for tools that require root)
* Running the image is that possible as either e.g. `1000:0` or `1000:1000`

**Comment by viceice** [comment]
@Chumper can you send a fix PR to make those paths readable by others? I would need to much time to fix the bats tests for now. 🙃

**Comment by maxbrunet** [comment]
Thank you @viceice and @Chumper!
