### ISSUE TITLE
User installs should be able to overwrite tool symlinks created by root installs

### ISSUE THREAD

**Issue by Chumper** [containerbase/buildpack#338]
When a root installs a tools the symlink in `/usr/local/bin` will have the mode `755` set.
This prevents user installs to overwrite symlinks when a user installs a tool.

We should change this to be `775` on created symlinks,

**Comment by Chumper** [comment]
The problem is not the symlink, but rather the shell wrapper.
The symlinks permission does not really matter:
```
Symlinks are always world readable/writeable.
```
from https://askubuntu.com/questions/1145107/mysql-server-config-file-permissions-on-ubuntu-18-04/1145114#1145114

The shell wrapper on the other hand is basically just a shell script and needs proper permissions.
For the case with `python` this needs a fix in the python tool, for all other tools in the `utils/linking.sh`.

**Comment by viceice** [comment]
Ok, so it seems we should always use shell wrapper scripts to not need change the target files.

**Comment by Chumper** [comment]
So no symlinks then?
We will always create a small shell script that simply calls the correct binary in the correct path?
We can do that.
In that case we would utilize `shell_wrapper` and `export_tool_env` more.

**Comment by viceice** [comment]
what about writing the shell wrapper as root only on prepare stage, and write the tool version to call to `/opt/...`, so the wrapper simply reads version and calls real binary. 🤔 

That way we won't need to make `/usr/local/bin` writable to users, as we don't need to overwrite the wrapper.

@rarkins WDYT? This would be again a major change and propably would allow us to solve #101

**Comment by viceice** [comment]
Yes, it's called on image build time for each tool seperate or all. So for language images we only like to prepare those, but on full image we like to prepare all.

something like this?
```sh
> prepare-tool all
> prepare-tool node
> prepare-tool node,python
```

**Comment by viceice** [comment]
@Chumper Let's fix the issue with small shell wrapper scripts now, so user can overwrite them. And in a later PR we can refactor handling for #101

**Comment by viceice** [comment]
As long as `/usr/local/bin` is writable by `user` we can already overwrite the links, so it works as expected.
