### ISSUE TITLE
Support erlang < 24

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#379]
```
> [2/3] RUN install-tool erlang:
  #11 5.840 Setting up libltdl7:amd64 (2.4.6-14) ...
  #11 5.845 Setting up libsctp1:amd64 (1.0.18+dfsg-1) ...
  #11 5.855 Setting up libodbc1:amd64 (2.3.6-0.1build1) ...
  #11 5.860 Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
  #11 12.18 linking tool erlang v22.3.4.25
  #11 12.20 /opt/buildpack/tools/erlang/22.3.4.25/bin/erl: 29: exec: /usr/local/erlang/22.3.4.25/erts-10.7.2.17/bin/erlexec: not found
  #11 12.20 
  #11 12.20 real	0m12.120s
  #11 12.20 user	0m8.357s
  #11 12.20 sys	0m1.717s
```

Elixir 1.7+ is still supported and needs erlang 19-22

https://hexdocs.pm/elixir/1.12.3/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by viceice** [comment]
https://github.com/renovatebot/docker-elixir/runs/6333976811?check_suite_focus=true

**Comment by Chumper** [comment]
Sounds to me that we should ensure the latest possible version of erlang is installed when somebody want to install elixir.
So like a small requirement table that either enforces the erland version and aborts or silently installs it.

**Comment by viceice** [comment]
I don't think we need a special version handling here, we don't do this for other tools like ruby / cocoapods.

We only need to make sure we can use older erlang / elixir versions. Renovate ant /or the user needs ti handle compability
