### ISSUE TITLE
Documentation of custom base image

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#4]
Not all users of this buildpack will necessarily use `containerbase/buildpack` as their base image. For some, they will want to:
- Substitute their own compatible (Ubuntu) base image
- Copy over necessary buildpack files
- Perform installs

The questions I have are:
- Should the buildpack be published independently, e.g. as a GitHub release archive, so that it can be used/copied without needing `containerbase/buildpack`? I *think* this wouldn't be necessary, and it would complicate our own process
- Can we someone reduce the necessary copy/bootstrap lines?

This is currently how such a scenario works:

```Dockerfile
FROM renovate/buildpack:4@sha256:bc40fb3708fb004ecd8b3a4f9a91ecb790d84e26da0a50c5a003ee3b494cd64e AS buildpack

FROM ubuntu:20.04 as base

# Set env and shell
ENV BASH_ENV=/usr/local/etc/env
SHELL ["/bin/bash" , "-c"]

# Set up buildpack
COPY --from=buildpack /usr/local/bin/ /usr/local/bin/
COPY --from=buildpack /usr/local/buildpack/ /usr/local/buildpack/
RUN install-buildpack
```

We should document this, and accept improvements to optimize it if people come up with them.

**Comment by viceice** [comment]
I've already added some basic docs, see https://github.com/containerbase/buildpack/blob/main/docs

**Comment by viceice** [comment]
We should add a renovate regex manager to update images in the docs, so they can be used via copy'n'paste.
