### ISSUE TITLE
Erlang broken

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#48]
![image](https://user-images.githubusercontent.com/6311784/118084132-74d2d900-b3c0-11eb-8bf2-0ae3846bc208.png)

This maybe affects anyone building with buildpack? :(

**Comment by viceice** [comment]
Did they changed the signing key. 😕

**Comment by rarkins** [comment]
I wasn't able to reproduce locally, very confusing

**Comment by viceice** [comment]
Where did it happen? Here on github actions?

**Comment by rarkins** [comment]
Yes actions keep failing

**Comment by rarkins** [comment]
It maybe unbroke itself: https://github.com/containerbase/buildpack/pull/46#issuecomment-840394756
