### ISSUE TITLE
Benchmark language/tool install times

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#5]
For each language we support (Java, Node, Python, etc) as well as the package managers used by Renovate (npm, yarn, Poetry, Bundler, etc) we should ideally have them benchmarked in this repo as part of our actions, e.g. so we know what the approximate time it takes to add each language/tool.

This will be particularly useful when we start looking into the feasibility of run-time installs.

**Comment by viceice** [comment]
From our github actions, most tools install in less than a minute.

**Comment by Chumper** [comment]
@rarkins In v2 we run a `time <install-tool>`. Is that sufficient?

**Comment by rarkins** [comment]
@Chumper sounds sufficient! Close this then?

**Comment by Chumper** [comment]
yes, please do :)

**Comment by viceice** [comment]
@Chumper you should also be able to close issues. 🤔

**Comment by Chumper** [comment]
> @Chumper you should also be able to close issues. 🤔

Indeed, I am. Never bothered to check. Good to know
