### ISSUE TITLE
New base using too much space

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#514]
```
FROM containerbase/buildpack:4.6.6
RUN install-tool java 11.0.12+7
```

= 503MB

```
FROM containerbase/buildpack:4.13.2
RUN install-tool java 11.0.12+7
```

= 779MB

**Comment by rarkins** [comment]
I'm checking it manually, will let you know

**Comment by rarkins** [comment]
Probably should have guessed it was https://github.com/containerbase/buildpack/pull/487

**Comment by rarkins** [comment]
Affects java, gradle, php, golang, ...more. Maybe a common v2 problem?

**Comment by viceice** [comment]
yes, seems some missing cleanup, can you check `/tmp` on build image? is there a buildpack directory?

https://github.com/containerbase/buildpack/blob/e5273bb85dc48fbe724614882b0a8f8d398cba29/src/usr/local/bin/install-tool#L38-L45

**Comment by viceice** [comment]
ok, yes. missing cleanup

**Comment by viceice** [comment]
ok, will check tomorrow
