### ISSUE TITLE
Additional cert env automated

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#519]
I've noticed users customizing Dockerfiles to add the following. Are any of these appropriate or necessary to add, or should they be unnecessary because we run `update-ca-certificates`? I have seen one user export these even after running `update-ca-certificates`.

- `SSL_CERT_FILE`
- `PIP_CERT` and `PIP_CLIENT_CERT` (Pip/Poetry/etc)
- `BUNDLE_SSL_CA_CERT` (Bundler)

**Comment by viceice** [comment]
they should follow https://github.com/containerbase/buildpack/blob/main/docs/custom-root-ca.md

So either use `update-ca-certificates` or defined env vars

**Comment by rarkins** [comment]
Are those variables not needed if certs are added at build time?

**Comment by viceice** [comment]
yes, they should be removed, but probably don't harm 😉
