### ISSUE TITLE
Rename `buildpack` to  `base`

### ISSUE THREAD

**Issue by viceice** [containerbase/buildpack#524]
We should rename `buildpack` to  `base` to remove confusions with CNCF `buildpacks`.

### Discussed in https://github.com/containerbase/buildpack/discussions/470

<div type='discussions-op-text'>

<sup>Originally posted by **jkutner** August  3, 2022</sup>
Does this project have any relationship to the CNCF project https://buildpacks.io/

Is this repo an implementation of CNB, or a does it provide a component that can be used with CNBs?</div>

**Comment by jkutner** [comment]
Can you provide an update on this issue? I'm hoping we can resolve this amicably without a bunch of lawyer stuff.

**Comment by rarkins** [comment]
Because time is limited, we're going to go with your original request:

> clarifying the name, and explaining this in the readme

See https://github.com/containerbase/buildpack/commit/ca7bc48756551675f3ba518875d0138d98e2002f

**Comment by jkutner** [comment]
@rarkins I consider that a stop-gap, but I am still requesting that you rename the project
