### ISSUE TITLE
Support `IGNORED_TOOLS` arg

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#54]
We should support a `IGNORED_TOOLS` build argument, which will be a comma-separated list. If the list is non-empty, any tool within should be skipped for `install-tool`.

Example: `IGNORED_TOOLS=PIPENV,HELM`

Maybe we can make it case-insensitive? e.g. allowing `IGNORED_TOOLS=pipenv,helm` too.

**Comment by viceice** [comment]
Sure, will make to lowercase before check

**Comment by rarkins** [comment]
Do we have an auto generated list of supported tool names anywhere yet?

**Comment by viceice** [comment]
no, not yet
