### ISSUE TITLE
Migrate test repos to this org

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#6]
We should use copy all test repositories into this org so that we don't depend on @renovate-testing's repos.

I'm thinking to use a prefix convention like `testing-`, e.g. `github.com/containerbase/testing-bundler`, etc.

**Comment by rarkins** [comment]
If our Actions here need to do a clone of such repos then it's a good idea to trim out any excess size files too, if they exist.

**Comment by viceice** [comment]
Migrate all test files to separate test repos to not have false positive vulnerabilities

**Comment by rarkins** [comment]
Do you mean move/remove even the test files in this repo? I'd prefer to keep them here if the only downside is false positive alerts

**Comment by viceice** [comment]
ok, in this case we can also move the files from the test repos to here 🤔

**Comment by rarkins** [comment]
Could work?

**Comment by viceice** [comment]
yes, on old buildpack i was simply to lazy to copy files 🙃 

So git calls where just some sugar for the tests but only if you check the logs
