### ISSUE TITLE
Automatically configure Node.js for custom certificates

### ISSUE THREAD

**Issue by rarkins** [containerbase/buildpack#61]
If custom certificates are provided, we should automatically configure Node.js to use them. By default they use their own bundled CA certs, so I think would ignore any custom certs added to Linux.

Should we configure `--use-openssl-ca` or `SSL_CERT_DIR` or `SSL_CERT_FILE`?

**Comment by viceice** [comment]
We can export `NODE_OPTIONS=--use-openssl-ca` when installing node

https://nodejs.org/api/cli.html#cli_node_options_options
https://nodejs.org/api/cli.html#cli_use_bundled_ca_use_openssl_ca
